### ISSUE TITLE
Copiar do arquivo PDF gerado causa aparecerem caracteres estranhos e separa letra de acento

### ISSUE THREAD

**Issue by xexeo** [COPPE-UFRJ/CoppeTeX#10]
Essa reclamação é do pessoal que arquiva a tese e tem que copia o resumo, mas acho que vale na prática para todo mundo que for citar a tese.

Alguns arquivos .pdf gerados, ao se fazer um Copy and Paste, geram os caracteres com o acento separado da letra e as ligaduras e outras coisas como caracteres estranhos.

Para isso funcionar é obrigado a usar:
\usepackage[T1]{fontenc},

Sugiro que isso seja posto no estilo.

**Comment by xexeo** [comment]
Explicação do porquê.

https://tex.stackexchange.com/questions/664/why-should-i-use-usepackaget1fontenc

**Comment by vicentehelano** [comment]
Ótimo explicação, professor Xexeo!

Você sugere incluir nos templates ou no interior da própria classe?

Um abraço,
Vicente Helano.



Em sex., 14 de fev. de 2020 às 15:11, Geraldo Xexeo <
notifications@github.com> escreveu:

**Comment by xexeo** [comment]
Como o suporte a português é inerente ao CoppeTeX, acho que podemos incluir na própria classe. 

Talvez colocar uma opção para trocar tanto o fontenc quanto o inputenc fosse a melhor solução.

Esses comandos são "encantamentos mágicos" que os usuários geralmente copiam sem saber para que servem. Tem gente que ainda usa \´e, por exemplo (vi isso outro dia), o que é resolvido pelo inputenc. Então escondê-los do usuário deixa o template mais limpo, e colocar uma interface de comando que faça mais sentido ajude.

**Comment by vicentehelano** [comment]
Certo.
Seria suficiente adicioná-los com o RequirePackage?

Um abraço,
Vicente Helano.

Em seg., 17 de fev. de 2020 às 11:24, Geraldo Xexeo <
notifications@github.com> escreveu:

**Comment by EduardoMangeli** [comment]
Existem duas questões sobre a codificação de caracteres, uma é a saída do pdf e outra é a entrada do texto no arquivo. https://tex.stackexchange.com/questions/44694/fontenc-vs-inputenc

A saída parece que pode ser resolvida como `\usepackage[T1]{fontenc}` sem maiores problemas. Então, acho que vale a pena incluir como `\RequirePackage` e vou fazer isso.

Quanto à entrada, eu costumo usar `\usepackage[utf8]{inputenc}` ou `\usepackage[utf8x]{inputenc}` para entrar caracteres acentuados mas isso é dependente da codificação de caracteres do arquivo de entrada. Além disso, as opções têm incompatibilidades diferentes. Impor isso ao usuário do template me parece ruim. https://tex.stackexchange.com/questions/13067/utf8x-vs-utf8-inputenc

Acho que vale a pena incluir uma opção `\usepackage[utf8x]{inputenc}` apenas no exemplo e comentar explicando.

**Comment by EduardoMangeli** [comment]
`RequirePakcage[T1]{fontenc}` incluído no commit 76684feb42bbd4a105b2bca402b182fc21aac76c

**Comment by xexeo** [comment]
Quem usa o lualatex (eu passei a usar agora, é bom), não precisa usar esse utf  inputenc, então passo a concordar com o colocar no exemplo apenas.

E citar para não usar com XeLaTex o LuaLaTeX

Além disso, tem uma ordem certa se usar (mesmo link explica)
\usepackage[T1]{fontenc} 
\usepackage[utf8]{inputenc}


Também descobri isso:
'The simple answer is that utf8x is to be avoided if possible. It loads the ucs package, which for a long time was unmaintained (although there is now a new maintainer) and breaks various other things.' (https://tex.stackexchange.com/questions/13067/utf8x-vs-utf8-inputenc) 

Considero que a inclusão do T1 fontenc encerra o issue, que deve ser ensinado a usar o utf8 **para pdflatex apenas** no exemplo.
