### ISSUE TITLE
Novos tipos: seminário de mestrado e generico

### ISSUE THREAD

**Issue by xexeo** [COPPE-UFRJ/CoppeTeX#15]
Sugiro a criação do tipo Seminário de mestrado e de mais um tipo generico onde poderia ser escrito qualquer coisa, com o uso de uma variável.

**Comment by EduardoMangeli** [comment]
Vou fazer esses e ver mais algumas coisas para o próximo commit

**Comment by xexeo** [comment]
Feche o issue quando fizer

**Comment by EduardoMangeli** [comment]
Exame de Qualificação de mestrado no commit fc8517e8e9307282c4bf2634719a2731d6e26ffc

**Comment by EduardoMangeli** [comment]
Para personalizar o template, basta redefinir os comandos que geram os nomes, no preâmbulo do documento, como abaixo:
```latex
\makeatletter
\renewcommand{\@degree}{Crt}
\renewcommand{\@degreename}{Carteirado}
\renewcommand{\local@degname}{Carteiro}
\renewcommand{\foreign@degname}{Mailman}
\renewcommand\local@doctype{Carta}
\renewcommand\foreign@doctype{Letter}
\makeatother
```

**Comment by xexeo** [comment]
Bah...
Discordo dessa abordagem, acho que devia ter um comando com 6 parâmetros que fizesse isso.
Alías, seu exemplo usa {} e depois não usa, como é o certo afinal?

**Comment by EduardoMangeli** [comment]
Sobre usar ou não  `{ }`:  _podem_ ser omitidos se o argumento for um token simples. Eu só repeti a estrutura interna da classe no exemplo de cima para mostrar como escrever qualquer coisa.

Vou cria um comando com seis argumentos. O código não vai ser muito diferente

**Comment by EduardoMangeli** [comment]
Criado o comando `freeconfig` no commit https://github.com/COPPE-UFRJ/CoppeTeX/commit/6e241254ed07f228c26be9bf2607282009a1a71f
