### ISSUE TITLE
Nova release

### ISSUE THREAD

**Issue by EduardoMangeli** [COPPE-UFRJ/CoppeTeX#21]
@vicentehelano, @xexeo 

Acho que podemos fazer uma realese (2.3) para minimizar algumas confusões. O quê vocês acham?

**Comment by vicentehelano** [comment]
Concordo, Eduardo!

Um abraço,
Vicente Helano.

Em seg, 7 de set de 2020 às 21:53, Eduardo Mangeli <notifications@github.com>
escreveu:

**Comment by xexeo** [comment]
Aproveitando essa release, deixar claro no README.md que estamos "dentro das normas emitidas no documento X, ou no dia X"

Acho também que o README tinha que ter algo em português.

**Comment by xexeo** [comment]
Vou colocar no texto do README (Revisada em 26/11/2019 – Alteração da Folha Aprovação, Anexo III, páginas 22 e 23)
