### ISSUE TITLE
Situação do CoppeTeX no CTAN e no Overleaf

### ISSUE THREAD

**Issue by xexeo** [COPPE-UFRJ/CoppeTeX#24]
Como ficaram essas coisas?

**Comment by EduardoMangeli** [comment]
A versão 2.3 está no overleaf https://www.overleaf.com/latex/templates/coppetex-2-dot-3-a-latex-toolkit-for-writing-thesis-and-dissertations/xbgnmkxnmksj

**Comment by nataliechaves** [comment]
Olá, poderiam me ajudar?
Estou utilizando o Overleaf para escrever minha tese e minha numeração nas referências bibliográficas está com a ordem errada. A Introdução está iniciando a primeira referência como [16].
Como posso corrigir isso? Estou usando coppe-unsrt.bst. Obrigada.

**Comment by EduardoMangeli** [comment]
> Olá, poderiam me ajudar? Estou utilizando o Overleaf para escrever minha tese e minha numeração nas referências bibliográficas está com a ordem errada. A Introdução está iniciando a primeira referência como [16]. Como posso corrigir isso? Estou usando coppe-unsrt.bst. Obrigada.

**Comment by EduardoMangeli** [comment]
Oi. Eu não entendi muito bem seu problema. Vou colocar uma cópia de um trecho do manual que eu espero que ajude a esclarecer alguma coisa. Além disso, garanta que você está usando a última versão do CoppeTeX

Do [manual](https://github.com/COPPE-UFRJ/CoppeTeX/blob/master/dist/coppe.pdf) , página 4:
"Thus, the CoppeTEX project designed two BibTEX styles, coppe-plain.bst and coppe-unsrt.bst. The coppe-plain.bst creates a list of references alphabetically sorted. The later is a numbered style, which sorts references by the order of citation."

**Comment by xexeo** [comment]
Olá Natalie,
  1. Para usar a última versão, use este repositório aqui para baixar.
  2. Por favor tente gerar um exemplo mínimo com o erro. 
  3. Erros bizarros como esse podem sempre ser resultado de arquivos temporários velhos. Por favor tente apagar todos os arquivos temporários e rodar latex/bibtex do zero.

**Comment by xexeo** [comment]
Transformado no issue https://github.com/COPPE-UFRJ/CoppeTeX/issues/42 #42

**Comment by nataliechaves** [comment]
segue onde foi iniciada a numeração. (Sou aluna do PEMM)
![image](https://user-images.githubusercontent.com/54603573/163392586-db7b8fee-5213-49c5-bbdd-cde33661b354.png)

**Comment by nataliechaves** [comment]
Acho que conseguei solucionar,  adicionei esse pacote \usepackage{notoccite}. Parece que está funcionando.

**Comment by EduardoMangeli** [comment]
Obrigado por compartilhar a solução que você encontrou, @nataliechaves! Será muito útil para os que enfrentarem o mesmo problema.
