### ISSUE TITLE
Numeração de Referências

### ISSUE THREAD

**Issue by bmazetto** [COPPE-UFRJ/CoppeTeX#29]
Prezados, 

Sou ainda iniciante no uso do LATeX, mas estou utilizando o template do CoppeTeX e não tenho tido muitas dificuldades. No entanto, há um ponto que ainda não sei como resolver e gostaria do auxílio da comunidade. Trata-se de uma confusão que surge na numeração das referências quando mando gerar as listas de figuras e de tabelas.

Algumas tabelas e figuras que coloquei ao longo do texto possuem citações. Quando mando gerar as listas de figuras e tabelas, a numeração das minhas referências se inicia pelas citações das listas na seção pré-textual e não pela seção de introdução no corpo do texto. Com isso, quando o texto principal se inicia, as primeiras referências já aparecem com numeração elevada ao invés de começar no [1].

Teriam alguma sugestão de como resolver esse ponto?

**Comment by Celger** [comment]
Prezado,
acredito que a resposta esteja em [https://tex.stackexchange.com/questions/36304/ignore-citations-in-captions-in-list-of-figures-when-numbering](url).
Inserir o pacote _notoccite_  ou declarar a legenda da seguinte forma:
`\caption[<Figure title>]{<Figure title> \cite{<Source>}}`

**Comment by bmazetto** [comment]
Adotei a alternativa do pacote _notoccite_ e parece que as listas da parte pré-textual não estão mais interferindo na numeração das referências.

Obrigado, @Celger!
