### ISSUE TITLE
Referências com nome e ano

### ISSUE THREAD

**Issue by felipemcabral** [COPPE-UFRJ/CoppeTeX#35]
Olá,

Gostaria de saber o que devo modificar para conseguir colocar as referências no formato (NOME, ANO) ou (NOME et al., ANO), sem que haja os números [1], [2].

Estou usando o Overleaf e tentei adicionar o pacote bibLaTeX, mas não obtive êxito. Tenho que mudar algo no .cls? ou diretamente no example.tex? Poderiam me ajudar, por favor?

**Comment by felipemcabral** [comment]
@xexeo

**Comment by xexeo** [comment]
Olá Felipe,
   
 No topo do exemplo dado para a tese da Coppe tem a opção numbers, é só retirá-la.
 
```
\documentclass[dsc,numbers]{coppe}
```
vira

```
\documentclass[dsc]{coppe}
```
     
Não resolvemos ainda a compatiblidade com o BibLaTeX, estamos ainda usando o BibTeX, mas não deve haver problemas após eliminar a opção.

Abraços,
Xexéo
