### ISSUE TITLE
Sugestões de melhorias

### ISSUE THREAD

**Issue by BrunoCampana** [COPPE-UFRJ/CoppeTeX#39]
Olá prezados, o pacote CoppeTeX ajudou-me enormemente, MUITO obrigado.

Como forma de agradecer, gostaria de sugerir algumas melhorias, **não para serem adicionadas diretamente ao pacote em si**, mas quem sabe para serem documentadas no repositório dicas ou na Wiki do pacote, porque ajudam muito, e tomaram-me um certo tempo para poder implementar no meu template de LaTeX (que é 100% baseado no CoppeTeX obviamente):

No repositório a seguir encontram-se as melhorias que fiz para meu template: 
[https://gitlab.com/brunocampana/latex-template-coppe-ufrj](https://gitlab.com/brunocampana/latex-template-coppe-ufrj)
1. Além da lista de figuras e de tabelas, adicionei lista de quadros e gráficos.
2. Removido o espaçamento antes do início de cada capítulo.
3. Adicionado suporte para epígrafes no início de cada capítulo.
4. Adicionado o campo "fonte" para tabelas, quadros, gráficos e figuras.
5. Adicionado apêndices com a palavra "Apêndice" no sumário (ToC).
6. Adicionado pontinhos no início de cada capítulo no sumário (ToC).
7. Adicionado suporte para ilustrações que ocupam a página toda em modo paisagem.
8. Adicionado suporte para tabelas espalhando-se por múltiplas páginas.
9. Adicionado capacidade de referência invertida em todo o documento.
10. Adicionado índice remissivo no documento.
11. Inserida indentação no primeiro parágrafo.
Por fim o principal:
12. Segmentação de cada capítulo em arquivo .tex separadamente, facilitando a redação dos capítulos e segregando mais o conteúdo do "grosso" da formatação editorial do arquivo .tex chamado "0principal.tex", que serve como root para a construção.

Como pode ver, são melhorias que não são relevantes para os já habituados com LaTeX, mas para os iniciantes pode poupar uns bons dias de trabalho.

Mais uma vez, agradeço!

**Comment by xexeo** [comment]
Bruno,
  Nós é que agradecemos. Muitas contribuições.
  Vamos certamente demorar para processar tudo, mas faremos referência ao seu repositório o mais rápido possível.
  Abraços,
  Xexéo
