### ISSUE TITLE
Como colocar página para examinadores assinarem?

### ISSUE THREAD

**Issue by gregluz** [COPPE-UFRJ/CoppeTeX#41]
Olá! Estou começando a usar o Latex agora e talvez a minha pergunta seja meio boba. Estou utilizando o template CoppeTex para fazer minha dissertação de mestrado. Contudo, não consigo criar o documento com aquela página para os examinadores assinarem depois da defesa. O documento depois de compilado já aparece com a página escrita Aprovada por: (nomes dos membros da banca).

Existe algum comando em que eu consiga alterar isso?

Abraços,

Gregório

**Comment by DurvalPimentel** [comment]
Olá, 
eu resolvi o meu problema alterando o código fonte no coppe.cls na parte onde o comando \makefrontpage é criado. 
Eu não tenho muito conhecimento nessa linguagem do LaTex e nem sou muito bom em programação então nem é nada muito automatizado. 
No meu caso eu tenho 3 examinadores e editei o código bem na força bruta pra isso. 
Segue a alteração a parte do código a ser alterada deve estar perto da linha 335  :

```
 \noindent\begin{tabularx}{\textwidth}[b]{@{}l@{ }>{\raggedleft\arraybackslash}X@{}}
    Aprovada por: \\ \\ & 
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ \\ &
    \count1=0
    \toks@={}
    \@whilenum \count1<\@examiner \do{%
   \ifnum 0= \count1 %
     \toks@=\expandafter{\csname CoppeExaminer:\the\count1%
        \expandafter\endcsname\expandafter\\ \\ \\ & \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ \\}
\else
\ifnum 1= \count1
         \toks@= \expandafter\expandafter\expandafter{%
        \expandafter\the\expandafter \toks@%
        \expandafter&\expandafter\space%
        \csname CoppeExaminer:\the\count1\expandafter\endcsname%
        \expandafter\space\\ \\ \\ & \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ \\ }%
\else
\ifnum 2= \count1
         \toks@= \expandafter\expandafter\expandafter{%
        \expandafter\the\expandafter \toks@%
        \expandafter&\expandafter\space%
        \csname CoppeExaminer:\the\count1\expandafter\endcsname%
        \expandafter\space\\ }%

 \fi
\fi
\fi

 
    \advance\count1 by 1}

    \the\toks@ & 
    \end{tabularx}}\par
```

**Comment by xexeo** [comment]
Caro Gregório,

 Os orientadores não assinam mais a capa, segundo o novo formato da Coppe.
 
Atenciosamente,
Geraldo Xexéo
