### ISSUE TITLE
Numeração errada ao usar unsorted

### ISSUE THREAD

**Issue by xexeo** [COPPE-UFRJ/CoppeTeX#42]
Olá, poderiam me ajudar?
Estou utilizando o Overleaf para escrever minha tese e minha numeração nas referências bibliográficas está com a ordem errada. A Introdução está iniciando a primeira referência como [16].
Como posso corrigir isso? Estou usando coppe-unsrt.bst. Obrigada.

_Originally posted by @nataliechaves in https://github.com/COPPE-UFRJ/CoppeTeX/issues/24#issuecomment-1095137966_

**Comment by EduardoMangeli** [comment]
Parece que usar o pacote [notoccite](https://www.ctan.org/pkg/notoccite) resolve o problema. 

https://github.com/COPPE-UFRJ/CoppeTeX/issues/24#issuecomment-1099160298

**Comment by xexeo** [comment]
Não era um problema do estilo, mas uma característica do LaTeX, é interessante conhecê-la.
