### ISSUE TITLE
Como adicionar " Acesso em:"  em \bibliographystyle{coppe-unsrt} importando as referências a partir do Mendeley/Overleaf

### ISSUE THREAD

**Issue by nataliechaves** [COPPE-UFRJ/CoppeTeX#43]
Olá a todos, 
Vocês poderiam me ajudar?

Estou importando minhas referências bibliográficas a partir do Mendeley(.bib) para o Overleaf com a versão atualizada da CoppeTeX.
Entretanto, alguns referências que deveriam vir com a informação de : "Acessado em:  " conforme a norma de elaboração de Teses COPPE/UFRJ esta informação não aparece. Mesmo "forçando" no meu arquivo .bib como no exemplo a seguir. Tem alguma ideia do que posso fazer para aparecer isso?

@generic{Lynch2017,
   abstract = {A computer scientist discusses artificial intelligence’s promise, hype, and biggest obstacles},
   author = {Shana Lynch},
   journal = {Insights by Stanford Business},
   month = {3},
   title = {Andrew Ng: Why AI Is the New Electricity},
   volume = {11},
   url = {ww.gsb.stanford.edu/insights/andrew-ng-why-ai-new-electricity},
   **urldate = {2022-04-23}** %add este item
   year = {2017},
}

Mas ainda assim, não carrega essa informação.

Agradeço desde já!

![image](https://user-images.githubusercontent.com/54603573/164950124-4e6c1454-b798-48f6-8db5-b97eb99f601c.png)

**Comment by nataliechaves** [comment]
Oi, 
sobre a questão anterior, 

"forcei" a aparecer "**Acesso em:** " inserido no código : <note = "Acesso em: 23 abr. 2022", > em substituição ao **urldate**

Entretanto, tenho outro ponto,

_Referência de tese e dissertação_ também não está no formato exigido.

exemplo pedido:
... **para dissertação/tese

> título (grifado)
> grau M.Sc./ D.Sc.
> instituição
> local
> ano da defesa** ...

![image](https://user-images.githubusercontent.com/54603573/164950854-72efd72d-9895-4806-863d-f683a95456ec.png)


Essa é a info que tem no meu .bib
![image](https://user-images.githubusercontent.com/54603573/164950869-37acfe31-9f42-4c24-a29a-4a11d3263979.png)

Gerando esta saída:
![image](https://user-images.githubusercontent.com/54603573/164950872-d77984f2-a998-427e-9b1d-d483cbb3481c.png)



Acredito que é alguma coisa do estilo, mas esse arquivo, não sei fazer modificação para mostras esse campos no .pdf. Alguém pode ajudar?


Att,

**Comment by xexeo** [comment]
Bem, o problema é que herdamos o CoppeTeX com o Bibtex e sem o campo urldate, que não é processado. Vamos colocar isso na lista de todos.

Enquanto isso, a solução é colocar o campo note mesmo.

A melhor mudança seria trocar para o BibLaTeX que já inclui os tipos online e www.

**Comment by xexeo** [comment]
Quanto ao segundo issue (por favor separe os issues, é mais fácil de ser tratado aqui). 
Vamos checar.
Só lembro que a Coppe nunca verificou as referências (kkk), mas realmente seria bom ter todas corretas.

**Comment by xexeo** [comment]
**Atenção**

  **No formato CoppeTeX deve ser usado a chave "access" e não "urldate".**
  Isso deve funcionar na maioria dos tipos de entrada.
  Não será, então, feita uma nova versão por enquanto.

**Comment by nataliechaves** [comment]
Oi, prof. 
Obrigada pelo retorno, farei como sugeriu.
